/*
 * KK Restaurant image library
 *
 * Images are served from Pexels' CDN. Pexels states that its photos can be
 * used for commercial websites; the individual photo pages are listed below.
 * The matcher deliberately prefers a dish-specific photo, then a very close
 * dish-family photo. Every menu item therefore has a real food image instead
 * of the old KK placeholder.
 */
import manual from './manual.json'

const p = (id, w = 900) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`

export const HERO = p(29850004, 1800)

// Verified / strongly matched Pexels photos.
const IMG = {
  tomatoSoup: p(6405531),
  cornSoup: p(7287700),
  hotSourSoup: p(36680510),
  mushroomSoup: p(24196190),
  chickenCornSoup: p(29538427),
  manchowSoup: p(8601410),
  chicken65: p(7353388),
  chickenLollipop: p(7868115),
  chilliChicken: p(28674534),
  chickenManchurian: p(35071821),
  paneerTikka: p(33430556),
  gobiManchurian: p(28674543),
  frenchFries: p(39799185),
  greenSalad: p(2750560),
  muttonCurry: p(28674565),
  fishFry: p(37316378),
  prawn: p(35696919),
  tandooriChicken: p(9609832),
  chickenTikka: p(30749024),
  naan: p(35066813),
  paratha: p(35079296),
  biryani: p(33947401),
  friedRice: p(32489477),
  noodles: p(4635600),
  dalMakhani: p(28674561),
  butterChicken: p(29685054),
  chickenCurry: p(10615283),
  paneerCurry: p(30858402),
  gulabJamun: p(11887844),
  iceCream: p(16015237),
  lassi: p(6808666),
  curry: p(33430557),
  dessert: p(3086863),
}

// Exact names where we have a particularly strong match.
const EXACT = {
  'Tomato Soup': IMG.tomatoSoup,
  'Sweet Corn Veg Soup': IMG.cornSoup,
  'Hot & Sour Veg / Mushroom Soup': IMG.hotSourSoup,
  'Cream Mushroom Soup': IMG.mushroomSoup,
  'Sweet Corn Chicken Soup': IMG.chickenCornSoup,
  'Hot & Sour Chicken Soup': IMG.hotSourSoup,
  'Chicken Manchow Soup': IMG.manchowSoup,
  'Chicken 65': IMG.chicken65,
  'Chicken Lollipop (Dry/Saucy)': IMG.chickenLollipop,
  'Chilli Chicken Dry': IMG.chilliChicken,
  'Chicken Manchurian Dry': IMG.chickenManchurian,
  'Gobi Manchurian Dry': IMG.gobiManchurian,
  'French Fries': IMG.frenchFries,
  'Green Salad': IMG.greenSalad,
  'Mutton Chukka': IMG.muttonCurry,
  'Mutton Pepper Fry': IMG.muttonCurry,
  'Fish Fry': IMG.fishFry,
  'Prawn 65': IMG.prawn,
  'Chilli Prawn Dry': IMG.prawn,
  'Prawn Fry / Pepper Fry': IMG.prawn,
  'Tandoori Chicken Half/Full': IMG.tandooriChicken,
  'Chicken Tikka': IMG.chickenTikka,
  'Garlic Naan': IMG.naan,
  'Plain Naan': IMG.naan,
  'Butter Naan': IMG.naan,
  'Paneer Kulcha': IMG.naan,
  'Tandoori Paratha': IMG.paratha,
  'Butter Paratha': IMG.paratha,
  'Pudina Paratha': IMG.paratha,
  'Chicken Biriyani': IMG.biryani,
  'Mutton Biriyani': IMG.biryani,
  'Prawn Biriyani': IMG.prawn,
  'Egg Biriyani': IMG.biryani,
  'Veg Fried Rice': IMG.friedRice,
  'Mushroom Fried Rice': IMG.friedRice,
  'Paneer Fried Rice': IMG.friedRice,
  'Chicken Fried Rice': IMG.friedRice,
  'Prawn Fried Rice': IMG.prawn,
  'Veg Noodles': IMG.noodles,
  'Chicken Noodles': IMG.noodles,
  'Prawn Noodles': IMG.prawn,
  'Dhal Makhani': IMG.dalMakhani,
  'Butter Chicken Masala': IMG.butterChicken,
  'Chicken Curry': IMG.chickenCurry,
  'Paneer Butter Masala': IMG.paneerCurry,
  'Gulab Jamun / with Ice Cream': IMG.gulabJamun,
  'Vanilla Ice Cream': IMG.iceCream,
  'Butterscotch Ice Cream': IMG.iceCream,
  'Strawberry Ice Cream': IMG.iceCream,
  'Mango Ice Cream': IMG.iceCream,
  'Chocolate Ice Cream': IMG.iceCream,
  'Pista Ice Cream': IMG.iceCream,
  'Black Currant Ice Cream': IMG.iceCream,
  'Sweet Lassi': IMG.lassi,
}

const rules = [
  [/egg/i, IMG.curry],
  [/pappad|papad/i, IMG.paratha],
  [/baby corn|corn.*dry/i, IMG.cornSoup],
  [/mushroom.*(dry|fry|manchurian)/i, IMG.mushroomSoup],
  [/gobi.*65/i, IMG.gobiManchurian],
  [/potato|aloo/i, IMG.frenchFries],
  [/dragon chicken|crispy fried chicken|bell pepper chicken|kothamalli chicken|lemon chicken|shangai chicken|chettinad chicken dry|chicken pepper fry|chicken chukka|garlic chicken dry|schezwan chicken dry/i, IMG.chicken65],
  [/crab/i, IMG.fishFry],
  [/squid/i, IMG.fishFry],
  [/tandoori paratha|tawa paratha|pudina paratha|butter paratha|plain roti|butter roti|chappathi/i, IMG.paratha],
  [/steam rice|jeera rice|ghee rice|pulav/i, IMG.friedRice],
  [/carrot halwa/i, IMG.dessert],
  [/brownie/i, IMG.dessert],
  [/fresh lemon soda|fresh lemon juice/i, IMG.lassi],
  [/soft drinks|water/i, IMG.lassi],
  [/tomato.*soup/i, IMG.tomatoSoup],
  [/sweet corn.*soup/i, IMG.cornSoup],
  [/corn.*chicken.*soup/i, IMG.chickenCornSoup],
  [/hot.*sour.*soup/i, IMG.hotSourSoup],
  [/manchow.*soup/i, IMG.manchowSoup],
  [/mushroom.*soup|cream mushroom/i, IMG.mushroomSoup],
  [/clear soup/i, IMG.tomatoSoup],
  [/soup/i, IMG.hotSourSoup],
  [/gobi.*manchurian/i, IMG.gobiManchurian],
  [/manchurian/i, IMG.chickenManchurian],
  [/paneer.*(tikka|pakoda|manchurian|pasinda)/i, IMG.paneerTikka],
  [/chilli.*paneer/i, IMG.paneerTikka],
  [/baby corn|corn.*dry/i, IMG.cornSoup],
  [/french fries/i, IMG.frenchFries],
  [/salad/i, IMG.greenSalad],
  [/chicken.*65/i, IMG.chicken65],
  [/lollipop/i, IMG.chickenLollipop],
  [/chilli chicken/i, IMG.chilliChicken],
  [/chicken.*manchurian/i, IMG.chickenManchurian],
  [/chicken.*(tikka|kebab|tangri|tandoori|rangeela|bannu|haryali|malai|kali mirchi)/i, IMG.chickenTikka],
  [/chicken|pozichakozhi/i, IMG.chickenCurry],
  [/mutton/i, IMG.muttonCurry],
  [/fish|nethili/i, IMG.fishFry],
  [/prawn|shrimp/i, IMG.prawn],
  [/squid|calamari/i, IMG.fishFry],
  [/naan|kulcha/i, IMG.naan],
  [/roti|chappathi/i, IMG.paratha],
  [/paratha/i, IMG.paratha],
  [/biriyani|biryani/i, IMG.biryani],
  [/fried rice|pulav|rice/i, IMG.friedRice],
  [/noodle|chopsuey/i, IMG.noodles],
  [/dal|dhal/i, IMG.dalMakhani],
  [/butter chicken/i, IMG.butterChicken],
  [/paneer/i, IMG.paneerCurry],
  [/curry|masala|kofta|channa|chana|aloo/i, IMG.curry],
  [/gulab/i, IMG.gulabJamun],
  [/halwa/i, IMG.dessert],
  [/brownie/i, IMG.dessert],
  [/ice cream|cassata/i, IMG.iceCream],
  [/lassi/i, IMG.lassi],
  [/lemon.*(soda|juice)/i, IMG.lassi],
  [/soft drinks|water/i, IMG.dessert],
]

export const imageFor = (name, category = '') => {
  if (manual[name]) return manual[name]
  if (EXACT[name]) return EXACT[name]
  const hit = rules.find(([re]) => re.test(name))
  if (hit) return hit[1]

  const categoryFallback = {
    soup: IMG.hotSourSoup,
    starter: IMG.gobiManchurian,
    chicken: IMG.chicken65,
    mutton: IMG.muttonCurry,
    seafood: IMG.fishFry,
    tandoori: IMG.tandooriChicken,
    bread: IMG.naan,
    biryani: IMG.biryani,
    rice: IMG.friedRice,
    noodles: IMG.noodles,
    curry: IMG.curry,
    dessert: IMG.dessert,
  }
  return categoryFallback[category] || IMG.curry
}

export const IMAGE_SOURCES = {
  'Pexels License': 'https://www.pexels.com/license/',
  'Tomato Soup': 'https://www.pexels.com/photo/close-up-shot-of-a-tomato-soup-6405531/',
  'Sweet Corn Soup': 'https://www.pexels.com/photo/close-up-photo-of-corn-soup-7287700/',
  'Hot & Sour Soup': 'https://www.pexels.com/photo/delicious-hot-and-sour-soup-in-white-bowl-36680510/',
  'Chicken Corn Soup': 'https://www.pexels.com/photo/delicious-chicken-corn-soup-in-white-bowl-29538427/',
  'Chicken 65': 'https://www.pexels.com/photo/chicken-65-style-fried-chicken-7353388/',
  'Chicken Lollipop': 'https://www.pexels.com/photo/chicken-lollipop-with-aluminum-foil-on-plate-7868115/',
  'Chicken Tikka': 'https://www.pexels.com/photo/delicious-chicken-tikka-on-black-skillet-30749024/',
  'Gobi Manchurian': 'https://www.pexels.com/photo/spicy-indo-chinese-gobi-manchurian-dish-28674543/',
  'Fish Fry': 'https://www.pexels.com/photo/traditional-indian-fish-fry-in-iron-kadhai-37316378/',
  'Prawn': 'https://www.pexels.com/photo/delicious-spicy-chilli-prawns-in-indian-wok-35696919/',
  'Tandoori Chicken': 'https://www.pexels.com/photo/tandoori-chicken-and-chutney-on-a-bowl-9609832/',
  'Naan': 'https://www.pexels.com/photo/delicious-garlic-naan-on-a-white-plate-35066813/',
  'Paratha': 'https://www.pexels.com/photo/close-up-of-fresh-indian-paratha-on-plate-35079296/',
  'Chicken Biryani': 'https://www.pexels.com/photo/authentic-chicken-biryani-in-clay-pot-33947401/',
  'Fried Rice': 'https://www.pexels.com/photo/delicious-indian-fried-rice-in-traditional-bowl-32489477/',
  'Noodles': 'https://www.pexels.com/photo/close-up-photo-of-noodles-4635600/',
  'Dal Makhani': 'https://www.pexels.com/photo/28674561/',
  'Butter Chicken': 'https://www.pexels.com/photo/delicious-indian-butter-chicken-in-copper-pan-29685054/',
  'Gulab Jamun': 'https://www.pexels.com/photo/close-up-photo-of-gulab-jamun-11887844/',
  'Ice Cream': 'https://www.pexels.com/photo/ice-cream-scoops-in-bowl-16015237/',
  'Lassi': 'https://www.pexels.com/photo/lassi-popular-indian-drink-6808666/',
}
